### ISSUE TITLE
Consider wiping away non-curried functions

### ISSUE THREAD

**Issue by conartist6** [sithmel/iter-tools#170] opened 2019-01-30 19:54 UTC
I'm sick of all this stuff where iter-tools functions may or may not be curried. It bloats our code, it complicates our type definitions, especially when there are other overloads, and I don't really see what it gets us. Why not just standardize on the double call notation of:
```js
function(...params)(...iterables)
```
Obviously this would be disruptive to all existing code which uses iter-tools, however it should be easy enough to publish a codemod which would automatically convert existing iter-tools usages.

I am not certain that we should do this, I just think it's worth a discussion.

**Comment by conartist6** [comment] 2019-01-30 20:12
Pros:
  - Easy to document/remember
  - Can get rid of duplication, much of which is done inconsistently anyway:
    - documentation
    - type definitions
    - type tests
    - runtime tests
  - Removing duplication has benefits:
    - saves library weight
    - eases contribution for us and future contribs
    - Removing duplication improves test coverage; some potential users may care!
Cons:
  - All syntax gets a little more verbose
  - Might dissuade some novice users who are not familiar with such a syntax and fear it
  - Looks more different when the expression does not fit all on one line
  - Some users may have never run a codemod, and have difficulty setting it up. Codemods can be hard to set up when your codebase includes nonstandard parser-level language features
  - Codemods may still be imperfect, and it is not possible to catch the case where an iter-tools function has been stored in a property or dynamic variable

**Comment by sithmel** [comment] 2019-01-30 20:37
The double call notation may appear weird to many. And it is inconvenient fir really simple use cases:
```js
function(...params)(...iterables)
```
is arguably less readable than:
```js
function(...params, ...iterables)
```
especially in the context of real code with other parenthesis involved.

I think the problem is that curry here is used inconsistently:
- sometimes using the curry function
- sometimes is not implemented
- sometimes I used custom curry with dynamic arguments

I would be happier to settle with the first everywhere

**Comment by conartist6** [comment] 2019-01-31 03:03
I do not think that that makes sense

**Comment by KSXGitHub** [comment] 2019-01-31 03:05
> I do not think that that makes sense

Which comment you was replying to?

**Comment by conartist6** [comment] 2019-01-31 03:52
Moving uncurried functions to other packages. It doesn't really make anything easier for anyone.

**Comment by KSXGitHub** [comment] 2019-01-31 04:06
Then I vote against it (at least until [partial application proposal](https://github.com/tc39/proposal-partial-application) get to stage 3), because this would make basic usage over complicated.

As for the issues you stated, I do not promise to solve them all, only some:

> Easy to document/remember

Only document non-curried use cases, we'll list curried use cases in relevant parts (such as pipeline, compose).

>   * runtime tests

We test `curry` function, we should be able to remove curried parts from the tests.

**Comment by sithmel** [comment] 2019-02-01 21:03
I have a crazy idea:
a custom curry version that curries until the last argument is an iterable/asyncIterable

This way I don't need the custom curry function for variadic functions

**Comment by conartist6** [comment] 2019-02-01 21:32
Yeah that would be a slightly better implementation of the curry helper that we have now that could then probably be used everywhere.

**Comment by KSXGitHub** [comment] 2019-02-02 00:01
On the contrary, if I have to choose, I prefer non curried functions.

**Comment by sithmel** [comment] 2019-02-05 00:05
closing this in favour of #185

**Closed by sithmel** 2019-02-05 00:05 UTC
Labels: discussion
